import Head from 'next/head';
import React from 'react';
import Cta from '../components/Cta';
import Div from '../components/Div';
import FunFact from '../components/FunFact';
import Layout from '../components/Layout';
import PageHeading from '../components/PageHeading';
import SectionHeading from '../components/SectionHeading';
import TeamSlider from '../components/Slider/TeamSlider';
import Spacing from '../components/Spacing';

export default function About() {
  const funfaceData = [
    {
      title: 'Happy Clients',
      factNumber: '10',
    },
    {
      title: 'Project Completed',
      factNumber: '12',
    },
    {
      title: 'Years Experience',
      factNumber: '3',
    },
  ];
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {/* Start Page Heading Section */}
        <PageHeading
          title="About me"
          bgSrc="images/about_hero_bg.jpeg"
          pageLinkText="About me"
        />
        {/* End Page Heading Section */}

        {/* Start About Section */}
        <Spacing lg="150" md="80" />
        <Div className="container">
          <Div className="row">
            <Div className="col-xl-5 col-lg-7">
              <SectionHeading
                title="My brief Biography"
                subtitle="About me"
              >
                <Spacing lg="30" md="20" />
                <p className="cs-m0">
                  I am a young man who has always been motivated to transend my current circumstances and not let my background define me. My educational journet started at Lily Academy for primary school, followed by Nairobi School. Currently, I am pursuing a degree in civil engineering and CPA studies at Strathmore University. One of my noteworthy accomplishments is maintaining perfect academic record. Recently, I founded "Maters Digital marketing," an agency where I channel my passion for graphic design and other crucial digital marketing skills. In addition to these skills, I have developed strong leadership qualities enabling me to navigate challenges effectively and inspire teams towards success.</p>
                <Spacing lg="30" md="30" />
                <Div className="cs-separator cs-accent_bg"></Div>
                <Spacing lg="25" md="40" />
              </SectionHeading>
            </Div>
            <Div className="col-lg-5 offset-xl-2">
              <img
                src="/images/about_img_1.jpeg"
                alt="About"
                className="w-100 cs-radius_15"
              />
              <Spacing lg="25" md="25" />
            </Div>
            
          </Div>
        </Div>
        <Spacing lg="75" md="55" />
        {/* End About Section */}

        {/* Start Fun Fact Section */}
        <Div className="container">
          <FunFact
            title="My fun fact"
            subtitle="I have a diverse skill set of crucial for digital marketing success. My strengths lie in gaphic design,web design and video editing, allowing me to create captivating content. I excel in social media marketing strategies to boost online presence and engagement. With strong leadership abilities, I guide teams to achieve marketing goals effectively"
            data={funfaceData}
          />
        </Div>
        {/* End Fun Fact Section */}

        {/* Start Why Choose Section */}
        <Spacing lg="100" md="80" />
        <Div className="container">
          <Div className="row">
            <Div className="col-xl-5 col-lg-6">
              <Div className="cs-image_layer cs-style1">
                <Div className="cs-image_layer_in">
                  <img
                    src="/images/about_img_4.jpeg"
                    alt="About"
                    className="w-100 cs-radius_15"
                  />
                </Div>
              </Div>
              <Spacing lg="0" md="40" />
            </Div>
            <Div className="col-xl-5 offset-xl-1 col-lg-6">
              <SectionHeading
                title="Highly experienced"
                subtitle="Why Choose Me"
              >
                <Spacing lg="30" md="20" />
                <p className="cs-m0">
                I prioritize delivering exceptional quality services to ensure the satisfaction and loyalty of my clients.
                </p>
                <Spacing lg="15" md="15" />
                <p className="cs-m0">
                Rather than constantly seeking new clients, my focus is on nurturing and maintaining strong relationships with the clients I have.
                </p>
                <Spacing lg="15" md="15" />
                <p className="cs-m0">
                By consistently exceeding expectations and providing tailored solutions, I aim to create lasting partnerships founded on trust, reliability, and mutual success.
                </p>
                <Spacing lg="30" md="30" />
                <Div className="cs-separator cs-accent_bg"></Div>
                <Spacing lg="25" md="0" />
              </SectionHeading>
            </Div>
          </Div>
        </Div>
        {/* End Why Choose Section */}

        {/* Start Team Section */}
        {/* <Spacing lg="145" md="80" />
        <Div className="container">
          <SectionHeading
            title="Awesome team <br/>members"
            subtitle="Our Team"
            variant="cs-style1"
          />
          <Spacing lg="85" md="45" />
          <TeamSlider />
        </Div> */}
        {/* End Team Section */}

        {/* Start CTA Section */}
        <Spacing lg="150" md="80" />
        <Div className="container">
          <Cta
            title="Let’s disscuse make <br />something <i>cool</i> together"
            btnText="Apply For Meeting"
            btnLink="/contact"
            bgSrc="/images/cta_bg.jpeg"
          />
        </Div>
        {/* End CTA Section */}
      </Layout>
    </>
  );
}
