import Head from 'next/head';
import CaseStudy from '../components/CaseStudy';
import Cta from '../components/Cta';
import Div from '../components/Div';
import Hero3 from '../components/Hero/Hero3';
import Layout from '../components/Layout';
import LogoList from '../components/LogoList';
import FunFact from '../components/FunFact';
import MovingText from '../components/MovingText';
import Portfolio2 from '../components/Portfolio/Portfolio2';
import Portfolio3 from '../components/Portfolio/Portfolio3';
import SectionHeading from '../components/SectionHeading';
import TestimonialSlider from '../components/Slider/TestimonialSlider';
import Spacing from '../components/Spacing';

export default function Home() {
  const heroSocialLinks = [
    {
      name: 'Instagram',
      links: 'https://www.instagram.com/c3d.rix._?igsh=bTdsYmJqcnBqZzI3',
    },
    {
      name: 'LinkedIn',
      links: 'https://www.linkedin.com/in/cedric-michael-njogu-48a146296?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app',
    },
  ];
  const funfaceData = [
    {
      title: 'Happy Clients',
      factNumber: '10',
    },
    {
      title: 'Project Completed',
      factNumber: '12',
    },
    {
      title: 'Years Experience',
      factNumber: '3',
    },
  ];
  
  

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {/* Start Hero Section */}
        <Hero3
          title="Njogu's<br />Portfolio"
          btnLink="contact"
          btnText={`Let's talk`}
          socialLinksHeading="Follow me"
          heroSocialLinks={heroSocialLinks}
          bgImageUrl="./images/hero_bg.jpeg"
        />
        {/* End Hero Section */}

      {/* Start About Section */}
      <Spacing lg="150" md="80" />
        <Div className="container">
          <Div className="row">
            <Div className="col-xl-5 col-lg-7">
              <SectionHeading
                title="My brief Biography"
                subtitle="About me"
              >
                <Spacing lg="30" md="20" />
                <p className="cs-m0">
                  I am a young man who has always been motivated to transend my current circumstances and not let my background define me. My educational journet started at Lily Academy for primary school, followed by Nairobi School. Currently, I am pursuing a degree in civil engineering and CPA studies at Strathmore University. One of my noteworthy accomplishments is maintaining perfect academic record. Recently, I founded "Maters Digital marketing," an agency where I channel my passion for graphic design and other cucial digital maketing skills. In addition to these skills, Ihave developed strong leadership qualities enabling me to navigate challenges effectively and inspie teams towards success.</p>
                <Spacing lg="30" md="30" />
                <Div className="cs-separator cs-accent_bg"></Div>
                <Spacing lg="25" md="40" />
              </SectionHeading>
            </Div>
            <Div className="col-lg-5 offset-xl-2">
              <img
                src="/images/about_img_1.jpeg"
                alt="About"
                className="w-100 cs-radius_15"
              />
              <Spacing lg="25" md="25" />
            </Div>
            
          </Div>
        </Div>
        <Spacing lg="75" md="55" />
        {/* End About Section */}


         {/* Start Fun Fact Section */}
         <Div className="container">
          <FunFact
            title="My fun fact"
            subtitle="I have a diverse skill set of crucial for digital marketing success. My strengths lie in gaphic design,web design and video editing, allowing me to create captivating content. I excel in social media marketing strategies to boost online presence and engagement. With strong leadership abilities, I guide teams to achieve marketing goals effectively"
            data={funfaceData}
          />
        </Div>
        {/* End Fun Fact Section */}

                {/* Start Why Choose Section */}
                <Spacing lg="100" md="80" />
        <Div className="container">
          <Div className="row">
            <Div className="col-xl-5 col-lg-6">
              <Div className="cs-image_layer cs-style1">
                <Div className="cs-image_layer_in">
                  <img
                    src="/images/about_img_4.jpeg"
                    alt="About"
                    className="w-100 cs-radius_15"
                  />
                </Div>
              </Div>
              <Spacing lg="0" md="40" />
            </Div>
            <Div className="col-xl-5 offset-xl-1 col-lg-6">
              <SectionHeading
                title="Highly experienced"
                subtitle="Why Choose Me"
              >
                <Spacing lg="30" md="20" />
                <p className="cs-m0">
                I prioritize delivering exceptional quality services to ensure the satisfaction and loyalty of my clients.
                </p>
                <Spacing lg="15" md="15" />
                <p className="cs-m0">
                Rather than constantly seeking new clients, my focus is on nurturing and maintaining strong relationships with the clients I have.
                </p>
                <Spacing lg="15" md="15" />
                <p className="cs-m0">
                By consistently exceeding expectations and providing tailored solutions, I aim to create lasting partnerships founded on trust, reliability, and mutual success.
                </p>
                <Spacing lg="30" md="30" />
                <Div className="cs-separator cs-accent_bg"></Div>
                <Spacing lg="25" md="0" />
              </SectionHeading>
            </Div>
          </Div>
        </Div>
        {/* End Why Choose Section */}

        {/* Start Case Study Section */}
        <Spacing lg="100" md="10" />
        <Div className="container">
          <SectionHeading
            title="Services"
            subtitle="Services Offered"
            variant="cs-style1 text-center"
          />
          <Spacing lg="90" md="45" />
        </Div>
        <CaseStudy
          title="Social media<br />management"
          bgUrl="/images/case_study_2.jpeg"
          href="/service/smm"
          variant="cs-style2"
        />
        <CaseStudy
          title="Logo & Graphics<br /> design"
          bgUrl="/images/case_study_1.jpeg"
          href="/service/logo&graphics"
        />
        <CaseStudy
          title="Ad management &<br />Digital marketing"
          bgUrl="/images/case_study_2.jpeg"
          href="/service/digitalmarketing"
          variant="cs-style2"
        />
        <CaseStudy
          title="Ads managment<br /> training"
          bgUrl="/images/case_study_1.jpeg"
          href="/service/ad-training"
        />
        <CaseStudy
          title="Video<br />Editing"
          bgUrl="/images/case_study_2.jpeg"
          href="/service/video-editing"
          variant="cs-style2"
        />
        <Spacing lg="150" md="80" />
        {/* End Case Study Section */}

        {/* Start Testimonial Section */}
        <TestimonialSlider />
        {/* End Testimonial Section */}

        {/* Start MovingText Section */}
        <Spacing lg="125" md="70" />
        <MovingText text="Graphic desinger/Social media marketer/Web Designer/" />
        <Spacing lg="105" md="70" />
        {/* End MovingText Section */}

        {/* Start LogoList Section */}
        <Div className="container">
          <LogoList />
        </Div>
        <Spacing lg="150" md="80" />
        {/* End LogoList Section */}

        {/* Start CTA Section */}
        <Div className="container">
          <Cta
            title="Let’s disscuss make <br />something <i>cool</i> together"
            btnText="Apply For Meeting"
            btnLink="/contact"
            bgSrc="/images/cta_bg_3.jpeg"
          />
        </Div>
        {/* End CTA Section */}
      </Layout>
    </>
  );
}
