import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react';
import Button from '../components/Button';
import Cta from '../components/Cta';
import Div from '../components/Div';
import Layout from '../components/Layout';
import PageHeading from '../components/PageHeading';
import SectionHeading from '../components/SectionHeading';
import Spacing from '../components/Spacing';

export default function Projects() {
  const router = useRouter();
  const portfolioId = router.query.portfolioId;
  return (
    <>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <PageHeading
          title="Projects"
          bgSrc="/images/service_hero_bg.jpeg"
          pageLinkText="Projects"
        />
        <Spacing lg="150" md="80" />
        <Div className="container">
          <img
            src="/images/portfolio_details_1.jpeg"
            alt="Details"
            className="cs-radius_15 w-100"
          />
          <Spacing lg="90" md="40" />
          <Div className="row">
            <Div className="col-lg-6">
              <SectionHeading title="The Goodstuff liquorstore" subtitle="Creative">
                <Spacing lg="40" md="20" />
                <p>
                I met an application online that they had posted and applied. I had an interview with them and they were satisfied with what I promised to offer. Till date they are still satisfied amd we still work together to tale the brand to the heights we'd love it to be in the near future. 
                </p>
                <Spacing lg="10" md="10" />
               {/*  <p>
                  Ipsum quia dolor sit amet, consectetur, adipisci velit, sed
                  quia non numquam eius modi tempora incidunt ut labore et
                  dolore magnam aliquam quaerat voluptatem. Ut enim ad minima
                  veniam, quis nostrum exercitationem ullam corporis suscipit.
                </p> */}
              </SectionHeading>
            </Div>
            <Div className="col-lg-5 offset-lg-1">
              <Spacing lg="60" md="40" />
              <h2 className="cs-font_30 cs-font_26_sm cs-m0">Project Info -</h2>
              <Spacing lg="50" md="30" />
              <Div className="row">
                <Div className="col-6">
                  <h3 className="cs-accent_color cs-font_22 cs-font_18_sm cs-m0">
                    Category:
                  </h3>
                  <p className="cs-m0">Web design || Social media marketing</p>
                  <Spacing lg="30" md="30" />
                </Div>
                <Div className="col-6">
                  <h3 className="cs-accent_color cs-font_22 cs-font_18_sm cs-m0">
                    Location:
                  </h3>
                  <p className="cs-m0">Nairobi,utawala.</p>
                  <Spacing lg="30" md="30" />
                </Div>
                {/* <Div className="col-6">
                  <h3 className="cs-accent_color cs-font_22 cs-font_18_sm cs-m0">
                    Software:
                  </h3>
                  <p className="cs-m0"></p>
                  <Spacing lg="30" md="30" />
                </Div> */}
                <Div className="col-6">
                  <h3 className="cs-accent_color cs-font_22 cs-font_18_sm cs-m0">
                    Start Date:
                  </h3>
                  <p className="cs-m0">Dec-2023</p>
                  <Spacing lg="30" md="30" />
                </Div>
                <Div className="col-6">
                  <h3 className="cs-accent_color cs-font_22 cs-font_18_sm cs-m0">
                    End Date: 
                  </h3>
                  <p className="cs-m0">Active Contract</p>
                  <Spacing lg="30" md="30" />
                </Div>
              </Div>
            </Div>
          </Div>
          <Spacing lg="65" md="10" />
          <Div className="cs-page_navigation cs-center">
            <Div>
              <Button
                btnLink="/projects"
                btnText="Prev Project"
                variant="cs-type1"
              />
            </Div>
            <Div>
              <Button
                btnLink="/projects-03"
                btnText="Next Project"
              />
            </Div>
          </Div>
        </Div>
        <Spacing lg="145" md="80" />
        <Cta onClick={() => window.open('mailto:cedricmicahelnjogu@gmail.com')} style={{ cursor: 'pointer' }}
          title="cedricmicahelnjogu@gmail.com"
          bgSrc="/images/cta_bg_2.jpeg"
          variant="rounded-0"
        />
      </Layout>
    </>
  );
}
